from utilities import binaryTree
root = None


if __name__ == '__main__':
    tree = binaryTree()
    # root = tree.insertion(root, 5)
    # root = tree.insertion(root, 4)
    # root = tree.insertion(root, 3)
    # root = tree.insertion(root, 2)
    # root = tree.insertion(root, 1)
    # root = tree.insertion(root, 6)
    # root = tree.insertion(root, 8)
    # root = tree.insertion(root, 7)
    # root = tree.insertion(root, 9)
    # root = tree.insertion(root, 10)
    root = tree.insertion(root, 20)
    root = tree.insertion(root, 22)
    root = tree.insertion(root, 8)
    root = tree.insertion(root, 4)
    root = tree.insertion(root, 12)
    root = tree.insertion(root, 10)
    root = tree.insertion(root, 14)
    root = tree.insertion(root, 23)
    root = tree.insertion(root, 25)
    print("boundary traversals")
    tree.leftSide(root)
    # print("left view of the tree")
    # tree.leftSide(root)
    # print("right view of the tree")
    # tree.rightSide(root)
    # print("left bottom")
    # tree.leftBottom(root)
    # print("right bottom")
    # tree.rightBottom(root)
